# 1 "actual_network.F90"
# 1 "<built-in>"
# 1 "<命令行>"

# 1 "/usr/include/stdc-predef.h" 1 3 4

# 17 "/usr/include/stdc-predef.h" 3 4























# 1 "<命令行>" 2
# 1 "actual_network.F90"

! DO NOT EDIT THIS FILE!!!
!
! This file is automatically generated by write_network.py at
! compile-time.
!
! To modify the species carried by the network, edit the appropriate inputs
! file.

! An automatically generated "null" network.  This provides the properties
! of a set of non-reacting species.
!
! nspec            -- the number of species
! naux             -- the number of auxiliary variables
!
! aion             -- atomic number
! zion             -- proton number
!
! spec_names       -- the name of the isotope
! short_spec_names -- an abbreviated form of the species name
!
! aux_names        -- the name of the auxiliary variable
! short_aux_names  -- an abbreviated form of the auxiliary variable


module actual_network

  use amrex_fort_module, only : rt => amrex_real

  implicit none

  integer, parameter :: nspec = 4
  integer, parameter :: nspec_evolve = 4
  integer, parameter :: naux =  0

  character (len=16), save :: spec_names(nspec) 
  character (len= 5), save :: short_spec_names(nspec)
  character (len=16), save :: aux_names(naux)
  character (len= 5), save :: short_aux_names(naux)

  double precision, allocatable, save :: aion(:), zion(:)

  !$acc declare create(aion, zion)





  integer, parameter :: nrates = 0
  integer, parameter :: num_rate_groups = 0

contains
  
  subroutine actual_network_init

    spec_names(1) = "carbon-12"
    spec_names(2) = "oxygen-16"
    spec_names(3) = "neon-20"
    spec_names(4) = "ash"

    short_spec_names(1) = "C12"
    short_spec_names(2) = "O16"
    short_spec_names(3) = "Ne20"
    short_spec_names(4) = "ash"

    allocate(aion(nspec))
    allocate(zion(nspec))

    aion(1) = 12.0
    aion(2) = 16.0
    aion(3) = 20.0
    aion(4) = 18.0

    zion(1) = 6.0
    zion(2) = 8.0
    zion(3) = 10.0
    zion(4) = 8.8


    !$acc update device(aion, zion)

  end subroutine actual_network_init



  subroutine actual_network_finalize

    implicit none

    deallocate(aion)
    deallocate(zion)

  end subroutine actual_network_finalize

end module actual_network
