! DO NOT EDIT THIS FILE!!!
!
! This file is automatically generated by write_probin.py at
! compile-time.
!
! To add a runtime parameter, do so by editting the appropriate _parameters
! file.

! This module stores the runtime parameters.  The probin_init() routine is
! used to initialize the runtime parameters

module extern_probin_module

  use amrex_fort_module, only: rt => amrex_real

  implicit none

  private

  real (kind=rt), save, public :: small_temp = 1.e5
  !$acc declare create(small_temp)
  real (kind=rt), save, public :: small_dens = 1.e5
  !$acc declare create(small_dens)
  logical, save, public :: use_eos_coulomb = .true.
  !$acc declare create(use_eos_coulomb)
  logical, save, public :: eos_input_is_constant = .true.
  !$acc declare create(eos_input_is_constant)
  real (kind=rt), save, public :: eos_ttol = 1.0d-8
  !$acc declare create(eos_ttol)
  real (kind=rt), save, public :: eos_dtol = 1.0d-8
  !$acc declare create(eos_dtol)
  real (kind=rt), save, public :: small_x = 1.d-30
  !$acc declare create(small_x)
  logical, save, public :: use_tables = .false.
  !$acc declare create(use_tables)
  logical, save, public :: use_c12ag_deboer17 = .false.
  !$acc declare create(use_c12ag_deboer17)
  logical, save, public :: do_constant_volume_burn = .false.
  !$acc declare create(do_constant_volume_burn)
  logical, save, public :: call_eos_in_rhs = .false.
  !$acc declare create(call_eos_in_rhs)
  real (kind=rt), save, public :: dT_crit = 1.0d20
  !$acc declare create(dT_crit)
  integer, save, public :: burning_mode = 1
  !$acc declare create(burning_mode)
  real (kind=rt), save, public :: burning_mode_factor = 1.d-1
  !$acc declare create(burning_mode_factor)
  logical, save, public :: integrate_temperature = .true.
  !$acc declare create(integrate_temperature)
  logical, save, public :: integrate_energy = .true.
  !$acc declare create(integrate_energy)
  integer, save, public :: jacobian = 1
  !$acc declare create(jacobian)
  logical, save, public :: centered_diff_jac = .false.
  !$acc declare create(centered_diff_jac)
  logical, save, public :: burner_verbose = .false.
  !$acc declare create(burner_verbose)
  real (kind=rt), save, public :: rtol_spec = 1.d-12
  !$acc declare create(rtol_spec)
  real (kind=rt), save, public :: rtol_temp = 1.d-6
  !$acc declare create(rtol_temp)
  real (kind=rt), save, public :: rtol_enuc = 1.d-6
  !$acc declare create(rtol_enuc)
  real (kind=rt), save, public :: atol_spec = 1.d-12
  !$acc declare create(atol_spec)
  real (kind=rt), save, public :: atol_temp = 1.d-6
  !$acc declare create(atol_temp)
  real (kind=rt), save, public :: atol_enuc = 1.d-6
  !$acc declare create(atol_enuc)
  logical, save, public :: retry_burn = .false.
  !$acc declare create(retry_burn)
  real (kind=rt), save, public :: retry_burn_factor = 1.25d0
  !$acc declare create(retry_burn_factor)
  real (kind=rt), save, public :: retry_burn_max_change = 1.0d2
  !$acc declare create(retry_burn_max_change)
  logical, save, public :: abort_on_failure = .true.
  !$acc declare create(abort_on_failure)
  logical, save, public :: renormalize_abundances = .false.
  !$acc declare create(renormalize_abundances)
  real (kind=rt), save, public :: SMALL_X_SAFE = 1.0d-30
  !$acc declare create(SMALL_X_SAFE)
  real (kind=rt), save, public :: MAX_TEMP = 1.0d11
  !$acc declare create(MAX_TEMP)
  real (kind=rt), save, public :: react_boost = -1.d0
  !$acc declare create(react_boost)
  real (kind=rt), save, public :: reactions_density_scale = 1.d0
  !$acc declare create(reactions_density_scale)
  real (kind=rt), save, public :: reactions_temperature_scale = 1.d0
  !$acc declare create(reactions_temperature_scale)
  real (kind=rt), save, public :: reactions_energy_scale = 1.d0
  !$acc declare create(reactions_energy_scale)
  integer, save, public :: ode_max_steps = 150000
  !$acc declare create(ode_max_steps)
  logical, save, public :: use_jacobian_caching = .true.
  !$acc declare create(use_jacobian_caching)

#ifdef AMREX_USE_CUDA
#endif

end module extern_probin_module

#ifdef COMPILE_WITH_F2PY
subroutine runtime_init(probin)

  use extern_probin_module

  implicit none

#else
subroutine runtime_init(name,namlen)

  use extern_probin_module

  implicit none

  integer :: namlen
  integer :: name(namlen)
#endif

  integer :: un, i, status

  integer, parameter :: maxlen = 256
  character (len=maxlen) :: probin


  namelist /extern/ small_temp
  namelist /extern/ small_dens
  namelist /extern/ use_eos_coulomb
  namelist /extern/ eos_input_is_constant
  namelist /extern/ eos_ttol
  namelist /extern/ eos_dtol
  namelist /extern/ small_x
  namelist /extern/ use_tables
  namelist /extern/ use_c12ag_deboer17
  namelist /extern/ do_constant_volume_burn
  namelist /extern/ call_eos_in_rhs
  namelist /extern/ dT_crit
  namelist /extern/ burning_mode
  namelist /extern/ burning_mode_factor
  namelist /extern/ integrate_temperature
  namelist /extern/ integrate_energy
  namelist /extern/ jacobian
  namelist /extern/ centered_diff_jac
  namelist /extern/ burner_verbose
  namelist /extern/ rtol_spec
  namelist /extern/ rtol_temp
  namelist /extern/ rtol_enuc
  namelist /extern/ atol_spec
  namelist /extern/ atol_temp
  namelist /extern/ atol_enuc
  namelist /extern/ retry_burn
  namelist /extern/ retry_burn_factor
  namelist /extern/ retry_burn_max_change
  namelist /extern/ abort_on_failure
  namelist /extern/ renormalize_abundances
  namelist /extern/ SMALL_X_SAFE
  namelist /extern/ MAX_TEMP
  namelist /extern/ react_boost
  namelist /extern/ reactions_density_scale
  namelist /extern/ reactions_temperature_scale
  namelist /extern/ reactions_energy_scale
  namelist /extern/ ode_max_steps
  namelist /extern/ use_jacobian_caching


  small_temp = 1.e5
  small_dens = 1.e5
  use_eos_coulomb = .true.
  eos_input_is_constant = .true.
  eos_ttol = 1.0d-8
  eos_dtol = 1.0d-8
  small_x = 1.d-30
  use_tables = .false.
  use_c12ag_deboer17 = .false.
  do_constant_volume_burn = .false.
  call_eos_in_rhs = .false.
  dT_crit = 1.0d20
  burning_mode = 1
  burning_mode_factor = 1.d-1
  integrate_temperature = .true.
  integrate_energy = .true.
  jacobian = 1
  centered_diff_jac = .false.
  burner_verbose = .false.
  rtol_spec = 1.d-12
  rtol_temp = 1.d-6
  rtol_enuc = 1.d-6
  atol_spec = 1.d-12
  atol_temp = 1.d-6
  atol_enuc = 1.d-6
  retry_burn = .false.
  retry_burn_factor = 1.25d0
  retry_burn_max_change = 1.0d2
  abort_on_failure = .true.
  renormalize_abundances = .false.
  SMALL_X_SAFE = 1.0d-30
  MAX_TEMP = 1.0d11
  react_boost = -1.d0
  reactions_density_scale = 1.d0
  reactions_temperature_scale = 1.d0
  reactions_energy_scale = 1.d0
  ode_max_steps = 150000
  use_jacobian_caching = .true.

#ifndef COMPILE_WITH_F2PY
  ! create the filename
#ifndef AMREX_USE_CUDA
  if (namlen > maxlen) then
     print *, 'probin file name too long'
     stop
  endif
#endif

  do i = 1, namlen
     probin(i:i) = char(name(i))
  end do


  ! read in the namelist
  un = 9
  open (unit=un, file=probin(1:namlen), form='formatted', status='old')
#else
  ! read in the namelist
  un = 9
  open (unit=un, file=trim(probin), form='formatted', status='old')
#endif
  read (unit=un, nml=extern, iostat=status)

  if (status < 0) then
     ! the namelist does not exist, so we just go with the defaults
     continue

  else if (status > 0) then
     ! some problem in the namelist
#ifndef AMREX_USE_CUDA 
     print *, 'ERROR: problem in the extern namelist'
#endif
     stop
  endif

  close (unit=un)

  !$acc update &
  !$acc device(small_temp, small_dens, use_eos_coulomb) &
  !$acc device(eos_input_is_constant, eos_ttol, eos_dtol) &
  !$acc device(small_x, use_tables, use_c12ag_deboer17) &
  !$acc device(do_constant_volume_burn, call_eos_in_rhs, dT_crit) &
  !$acc device(burning_mode, burning_mode_factor, integrate_temperature) &
  !$acc device(integrate_energy, jacobian, centered_diff_jac) &
  !$acc device(burner_verbose, rtol_spec, rtol_temp) &
  !$acc device(rtol_enuc, atol_spec, atol_temp) &
  !$acc device(atol_enuc, retry_burn, retry_burn_factor) &
  !$acc device(retry_burn_max_change, abort_on_failure, renormalize_abundances) &
  !$acc device(SMALL_X_SAFE, MAX_TEMP, react_boost) &
  !$acc device(reactions_density_scale, reactions_temperature_scale, reactions_energy_scale) &
  !$acc device(ode_max_steps, use_jacobian_caching)

end subroutine runtime_init

