! DO NOT EDIT THIS FILE!!!
!
! This file is automatically generated by write_probin.py at
! compile-time.
!
! To add a runtime parameter, do so by editting the appropriate _parameters
! file.

! This module stores the runtime parameters.  The probin_init() routine is
! used to initialize the runtime parameters

! this version is a stub -- useful for when we only need a container for
! parameters, but not for MAESTRO use.

module probin_module

  use amrex_fort_module, only : rt => amrex_real

  implicit none

  private

  real (kind=rt), save, public :: velpert_amplitude = 1.e5
  !$acc declare create(velpert_amplitude)
  real (kind=rt), save, public :: velpert_radius = 2.e7
  !$acc declare create(velpert_radius)
  real (kind=rt), save, public :: velpert_scale = 1.e7
  !$acc declare create(velpert_scale)
  real (kind=rt), save, public :: velpert_steep = 1.e5
  !$acc declare create(velpert_steep)
  real (kind=rt), save, public :: tag_density_1 = 5.e7
  !$acc declare create(tag_density_1)
  real (kind=rt), save, public :: tag_density_2 = 1.e8
  !$acc declare create(tag_density_2)
  real (kind=rt), save, public :: tag_density_3 = 1.e8
  !$acc declare create(tag_density_3)
  real (kind=rt), save, public :: particle_temp_cutoff = 6.e8
  !$acc declare create(particle_temp_cutoff)
  real (kind=rt), save, public :: particle_tpert_threshold = 2.e7
  !$acc declare create(particle_tpert_threshold)

#ifdef CUDA
#endif

end module probin_module


module extern_probin_module

  use amrex_fort_module, only : rt => amrex_real

  implicit none

  private

  logical, save, public :: use_eos_coulomb = .true.
  !$acc declare create(use_eos_coulomb)
  logical, save, public :: eos_input_is_constant = .true.
  !$acc declare create(eos_input_is_constant)
  real (kind=rt), save, public :: eos_ttol = 1.0d-8
  !$acc declare create(eos_ttol)
  real (kind=rt), save, public :: eos_dtol = 1.0d-8
  !$acc declare create(eos_dtol)
  real (kind=rt), save, public :: small_x = 1.d-30
  !$acc declare create(small_x)
  logical, save, public :: disable_fermi_heating = .false.
  !$acc declare create(disable_fermi_heating)
  logical, save, public :: use_tables = .false.
  !$acc declare create(use_tables)
  logical, save, public :: use_c12ag_deboer17 = .false.
  !$acc declare create(use_c12ag_deboer17)
  integer, save, public :: ode_max_steps = 150000
  !$acc declare create(ode_max_steps)
  integer, save, public :: scaling_method = 2
  !$acc declare create(scaling_method)
  logical, save, public :: use_timestep_estimator = .false.
  !$acc declare create(use_timestep_estimator)
  real (kind=rt), save, public :: ode_scale_floor = 1.d-6
  !$acc declare create(ode_scale_floor)
  integer, save, public :: ode_method = 1
  !$acc declare create(ode_method)
  real (kind=rt), save, public :: safety_factor = 1.d9
  !$acc declare create(safety_factor)
  logical, save, public :: do_constant_volume_burn = .false.
  !$acc declare create(do_constant_volume_burn)
  logical, save, public :: call_eos_in_rhs = .false.
  !$acc declare create(call_eos_in_rhs)
  real (kind=rt), save, public :: dT_crit = 1.0d20
  !$acc declare create(dT_crit)
  integer, save, public :: burning_mode = 1
  !$acc declare create(burning_mode)
  real (kind=rt), save, public :: burning_mode_factor = 1.d-1
  !$acc declare create(burning_mode_factor)
  logical, save, public :: integrate_temperature = .true.
  !$acc declare create(integrate_temperature)
  logical, save, public :: integrate_energy = .true.
  !$acc declare create(integrate_energy)
  integer, save, public :: jacobian = 1
  !$acc declare create(jacobian)
  logical, save, public :: centered_diff_jac = .false.
  !$acc declare create(centered_diff_jac)
  logical, save, public :: burner_verbose = .false.
  !$acc declare create(burner_verbose)
  real (kind=rt), save, public :: rtol_spec = 1.d-12
  !$acc declare create(rtol_spec)
  real (kind=rt), save, public :: rtol_temp = 1.d-6
  !$acc declare create(rtol_temp)
  real (kind=rt), save, public :: rtol_enuc = 1.d-6
  !$acc declare create(rtol_enuc)
  real (kind=rt), save, public :: atol_spec = 1.d-12
  !$acc declare create(atol_spec)
  real (kind=rt), save, public :: atol_temp = 1.d-6
  !$acc declare create(atol_temp)
  real (kind=rt), save, public :: atol_enuc = 1.d-6
  !$acc declare create(atol_enuc)
  logical, save, public :: retry_burn = .false.
  !$acc declare create(retry_burn)
  real (kind=rt), save, public :: retry_burn_factor = 1.25d0
  !$acc declare create(retry_burn_factor)
  real (kind=rt), save, public :: retry_burn_max_change = 1.0d2
  !$acc declare create(retry_burn_max_change)
  logical, save, public :: abort_on_failure = .true.
  !$acc declare create(abort_on_failure)
  logical, save, public :: renormalize_abundances = .false.
  !$acc declare create(renormalize_abundances)
  real (kind=rt), save, public :: SMALL_X_SAFE = 1.0d-30
  !$acc declare create(SMALL_X_SAFE)
  real (kind=rt), save, public :: MAX_TEMP = 1.0d11
  !$acc declare create(MAX_TEMP)
  real (kind=rt), save, public :: react_boost = -1.d0
  !$acc declare create(react_boost)
  real (kind=rt), save, public :: reactions_density_scale = 1.d0
  !$acc declare create(reactions_density_scale)
  real (kind=rt), save, public :: reactions_temperature_scale = 1.d0
  !$acc declare create(reactions_temperature_scale)
  real (kind=rt), save, public :: reactions_energy_scale = 1.d0
  !$acc declare create(reactions_energy_scale)

#ifdef CUDA
#endif

end module extern_probin_module


module runtime_init_module

  use amrex_error_module
  use amrex_fort_module, only : rt => amrex_real
  use probin_module
  use extern_probin_module
  use amrex_parmparse_module

  implicit none

  namelist /probin/ velpert_amplitude
  namelist /probin/ velpert_radius
  namelist /probin/ velpert_scale
  namelist /probin/ velpert_steep
  namelist /probin/ tag_density_1
  namelist /probin/ tag_density_2
  namelist /probin/ tag_density_3
  namelist /probin/ particle_temp_cutoff
  namelist /probin/ particle_tpert_threshold
  namelist /probin/ use_eos_coulomb
  namelist /probin/ eos_input_is_constant
  namelist /probin/ eos_ttol
  namelist /probin/ eos_dtol
  namelist /probin/ small_x
  namelist /probin/ disable_fermi_heating
  namelist /probin/ use_tables
  namelist /probin/ use_c12ag_deboer17
  namelist /probin/ ode_max_steps
  namelist /probin/ scaling_method
  namelist /probin/ use_timestep_estimator
  namelist /probin/ ode_scale_floor
  namelist /probin/ ode_method
  namelist /probin/ safety_factor
  namelist /probin/ do_constant_volume_burn
  namelist /probin/ call_eos_in_rhs
  namelist /probin/ dT_crit
  namelist /probin/ burning_mode
  namelist /probin/ burning_mode_factor
  namelist /probin/ integrate_temperature
  namelist /probin/ integrate_energy
  namelist /probin/ jacobian
  namelist /probin/ centered_diff_jac
  namelist /probin/ burner_verbose
  namelist /probin/ rtol_spec
  namelist /probin/ rtol_temp
  namelist /probin/ rtol_enuc
  namelist /probin/ atol_spec
  namelist /probin/ atol_temp
  namelist /probin/ atol_enuc
  namelist /probin/ retry_burn
  namelist /probin/ retry_burn_factor
  namelist /probin/ retry_burn_max_change
  namelist /probin/ abort_on_failure
  namelist /probin/ renormalize_abundances
  namelist /probin/ SMALL_X_SAFE
  namelist /probin/ MAX_TEMP
  namelist /probin/ react_boost
  namelist /probin/ reactions_density_scale
  namelist /probin/ reactions_temperature_scale
  namelist /probin/ reactions_energy_scale

  private

  public :: probin

  public :: runtime_init, runtime_close, runtime_pretty_print

contains

subroutine runtime_init()

  implicit none

  integer :: status

  velpert_amplitude = 1.e5
  velpert_radius = 2.e7
  velpert_scale = 1.e7
  velpert_steep = 1.e5
  tag_density_1 = 5.e7
  tag_density_2 = 1.e8
  tag_density_3 = 1.e8
  particle_temp_cutoff = 6.e8
  particle_tpert_threshold = 2.e7
  use_eos_coulomb = .true.
  eos_input_is_constant = .true.
  eos_ttol = 1.0d-8
  eos_dtol = 1.0d-8
  small_x = 1.d-30
  disable_fermi_heating = .false.
  use_tables = .false.
  use_c12ag_deboer17 = .false.
  ode_max_steps = 150000
  scaling_method = 2
  use_timestep_estimator = .false.
  ode_scale_floor = 1.d-6
  ode_method = 1
  safety_factor = 1.d9
  do_constant_volume_burn = .false.
  call_eos_in_rhs = .false.
  dT_crit = 1.0d20
  burning_mode = 1
  burning_mode_factor = 1.d-1
  integrate_temperature = .true.
  integrate_energy = .true.
  jacobian = 1
  centered_diff_jac = .false.
  burner_verbose = .false.
  rtol_spec = 1.d-12
  rtol_temp = 1.d-6
  rtol_enuc = 1.d-6
  atol_spec = 1.d-12
  atol_temp = 1.d-6
  atol_enuc = 1.d-6
  retry_burn = .false.
  retry_burn_factor = 1.25d0
  retry_burn_max_change = 1.0d2
  abort_on_failure = .true.
  renormalize_abundances = .false.
  SMALL_X_SAFE = 1.0d-30
  MAX_TEMP = 1.0d11
  react_boost = -1.d0
  reactions_density_scale = 1.d0
  reactions_temperature_scale = 1.d0
  reactions_energy_scale = 1.d0


  ! read in the namelist
  read (amrex_namelist, nml=probin, iostat=status)

  if (status .ne. 0) then
     ! some problem in the namelist
     print *, 'ERROR: problem in the namelist'
     stop
  endif

  !$acc update &
  !$acc device(velpert_amplitude, velpert_radius, velpert_scale) &
  !$acc device(velpert_steep, tag_density_1, tag_density_2) &
  !$acc device(tag_density_3, particle_temp_cutoff, particle_tpert_threshold) &
  !$acc device(use_eos_coulomb, eos_input_is_constant, eos_ttol) &
  !$acc device(eos_dtol, small_x, disable_fermi_heating) &
  !$acc device(use_tables, use_c12ag_deboer17, ode_max_steps) &
  !$acc device(scaling_method, use_timestep_estimator, ode_scale_floor) &
  !$acc device(ode_method, safety_factor, do_constant_volume_burn) &
  !$acc device(call_eos_in_rhs, dT_crit, burning_mode) &
  !$acc device(burning_mode_factor, integrate_temperature, integrate_energy) &
  !$acc device(jacobian, centered_diff_jac, burner_verbose) &
  !$acc device(rtol_spec, rtol_temp, rtol_enuc) &
  !$acc device(atol_spec, atol_temp, atol_enuc) &
  !$acc device(retry_burn, retry_burn_factor, retry_burn_max_change) &
  !$acc device(abort_on_failure, renormalize_abundances, SMALL_X_SAFE) &
  !$acc device(MAX_TEMP, react_boost, reactions_density_scale) &
  !$acc device(reactions_temperature_scale, reactions_energy_scale)

end subroutine runtime_init

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  subroutine runtime_close()

    use probin_module


  end subroutine runtime_close

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

subroutine runtime_pretty_print(unit) bind(C, name="runtime_pretty_print")

    use amrex_constants_module
    use probin_module
    use extern_probin_module

    integer, intent(in) :: unit

    logical :: ltest

    write (unit, *) "[*] indicates overridden default"

100 format (1x, a3, 2x, a32, 1x, "=", 1x, a)
101 format (1x, a3, 2x, a32, 1x, "=", 1x, i10)
102 format (1x, a3, 2x, a32, 1x, "=", 1x, g20.10)
103 format (1x, a3, 2x, a32, 1x, "=", 1x, l)

    ltest = velpert_amplitude == 1.e5
    write (unit,102) merge("   ", "[*]", ltest), &
 "velpert_amplitude", velpert_amplitude

    ltest = velpert_radius == 2.e7
    write (unit,102) merge("   ", "[*]", ltest), &
 "velpert_radius", velpert_radius

    ltest = velpert_scale == 1.e7
    write (unit,102) merge("   ", "[*]", ltest), &
 "velpert_scale", velpert_scale

    ltest = velpert_steep == 1.e5
    write (unit,102) merge("   ", "[*]", ltest), &
 "velpert_steep", velpert_steep

    ltest = tag_density_1 == 5.e7
    write (unit,102) merge("   ", "[*]", ltest), &
 "tag_density_1", tag_density_1

    ltest = tag_density_2 == 1.e8
    write (unit,102) merge("   ", "[*]", ltest), &
 "tag_density_2", tag_density_2

    ltest = tag_density_3 == 1.e8
    write (unit,102) merge("   ", "[*]", ltest), &
 "tag_density_3", tag_density_3

    ltest = particle_temp_cutoff == 6.e8
    write (unit,102) merge("   ", "[*]", ltest), &
 "particle_temp_cutoff", particle_temp_cutoff

    ltest = particle_tpert_threshold == 2.e7
    write (unit,102) merge("   ", "[*]", ltest), &
 "particle_tpert_threshold", particle_tpert_threshold

    ltest = use_eos_coulomb .eqv. .true.
    write (unit,103) merge("   ", "[*]", ltest), &
 "use_eos_coulomb", use_eos_coulomb

    ltest = eos_input_is_constant .eqv. .true.
    write (unit,103) merge("   ", "[*]", ltest), &
 "eos_input_is_constant", eos_input_is_constant

    ltest = eos_ttol == 1.0d-8
    write (unit,102) merge("   ", "[*]", ltest), &
 "eos_ttol", eos_ttol

    ltest = eos_dtol == 1.0d-8
    write (unit,102) merge("   ", "[*]", ltest), &
 "eos_dtol", eos_dtol

    ltest = small_x == 1.d-30
    write (unit,102) merge("   ", "[*]", ltest), &
 "small_x", small_x

    ltest = disable_fermi_heating .eqv. .false.
    write (unit,103) merge("   ", "[*]", ltest), &
 "disable_fermi_heating", disable_fermi_heating

    ltest = use_tables .eqv. .false.
    write (unit,103) merge("   ", "[*]", ltest), &
 "use_tables", use_tables

    ltest = use_c12ag_deboer17 .eqv. .false.
    write (unit,103) merge("   ", "[*]", ltest), &
 "use_c12ag_deboer17", use_c12ag_deboer17

    ltest = ode_max_steps == 150000
    write (unit,101) merge("   ", "[*]", ltest), &
 "ode_max_steps", ode_max_steps

    ltest = scaling_method == 2
    write (unit,101) merge("   ", "[*]", ltest), &
 "scaling_method", scaling_method

    ltest = use_timestep_estimator .eqv. .false.
    write (unit,103) merge("   ", "[*]", ltest), &
 "use_timestep_estimator", use_timestep_estimator

    ltest = ode_scale_floor == 1.d-6
    write (unit,102) merge("   ", "[*]", ltest), &
 "ode_scale_floor", ode_scale_floor

    ltest = ode_method == 1
    write (unit,101) merge("   ", "[*]", ltest), &
 "ode_method", ode_method

    ltest = safety_factor == 1.d9
    write (unit,102) merge("   ", "[*]", ltest), &
 "safety_factor", safety_factor

    ltest = do_constant_volume_burn .eqv. .false.
    write (unit,103) merge("   ", "[*]", ltest), &
 "do_constant_volume_burn", do_constant_volume_burn

    ltest = call_eos_in_rhs .eqv. .false.
    write (unit,103) merge("   ", "[*]", ltest), &
 "call_eos_in_rhs", call_eos_in_rhs

    ltest = dT_crit == 1.0d20
    write (unit,102) merge("   ", "[*]", ltest), &
 "dT_crit", dT_crit

    ltest = burning_mode == 1
    write (unit,101) merge("   ", "[*]", ltest), &
 "burning_mode", burning_mode

    ltest = burning_mode_factor == 1.d-1
    write (unit,102) merge("   ", "[*]", ltest), &
 "burning_mode_factor", burning_mode_factor

    ltest = integrate_temperature .eqv. .true.
    write (unit,103) merge("   ", "[*]", ltest), &
 "integrate_temperature", integrate_temperature

    ltest = integrate_energy .eqv. .true.
    write (unit,103) merge("   ", "[*]", ltest), &
 "integrate_energy", integrate_energy

    ltest = jacobian == 1
    write (unit,101) merge("   ", "[*]", ltest), &
 "jacobian", jacobian

    ltest = centered_diff_jac .eqv. .false.
    write (unit,103) merge("   ", "[*]", ltest), &
 "centered_diff_jac", centered_diff_jac

    ltest = burner_verbose .eqv. .false.
    write (unit,103) merge("   ", "[*]", ltest), &
 "burner_verbose", burner_verbose

    ltest = rtol_spec == 1.d-12
    write (unit,102) merge("   ", "[*]", ltest), &
 "rtol_spec", rtol_spec

    ltest = rtol_temp == 1.d-6
    write (unit,102) merge("   ", "[*]", ltest), &
 "rtol_temp", rtol_temp

    ltest = rtol_enuc == 1.d-6
    write (unit,102) merge("   ", "[*]", ltest), &
 "rtol_enuc", rtol_enuc

    ltest = atol_spec == 1.d-12
    write (unit,102) merge("   ", "[*]", ltest), &
 "atol_spec", atol_spec

    ltest = atol_temp == 1.d-6
    write (unit,102) merge("   ", "[*]", ltest), &
 "atol_temp", atol_temp

    ltest = atol_enuc == 1.d-6
    write (unit,102) merge("   ", "[*]", ltest), &
 "atol_enuc", atol_enuc

    ltest = retry_burn .eqv. .false.
    write (unit,103) merge("   ", "[*]", ltest), &
 "retry_burn", retry_burn

    ltest = retry_burn_factor == 1.25d0
    write (unit,102) merge("   ", "[*]", ltest), &
 "retry_burn_factor", retry_burn_factor

    ltest = retry_burn_max_change == 1.0d2
    write (unit,102) merge("   ", "[*]", ltest), &
 "retry_burn_max_change", retry_burn_max_change

    ltest = abort_on_failure .eqv. .true.
    write (unit,103) merge("   ", "[*]", ltest), &
 "abort_on_failure", abort_on_failure

    ltest = renormalize_abundances .eqv. .false.
    write (unit,103) merge("   ", "[*]", ltest), &
 "renormalize_abundances", renormalize_abundances

    ltest = SMALL_X_SAFE == 1.0d-30
    write (unit,102) merge("   ", "[*]", ltest), &
 "SMALL_X_SAFE", SMALL_X_SAFE

    ltest = MAX_TEMP == 1.0d11
    write (unit,102) merge("   ", "[*]", ltest), &
 "MAX_TEMP", MAX_TEMP

    ltest = react_boost == -1.d0
    write (unit,102) merge("   ", "[*]", ltest), &
 "react_boost", react_boost

    ltest = reactions_density_scale == 1.d0
    write (unit,102) merge("   ", "[*]", ltest), &
 "reactions_density_scale", reactions_density_scale

    ltest = reactions_temperature_scale == 1.d0
    write (unit,102) merge("   ", "[*]", ltest), &
 "reactions_temperature_scale", reactions_temperature_scale

    ltest = reactions_energy_scale == 1.d0
    write (unit,102) merge("   ", "[*]", ltest), &
 "reactions_energy_scale", reactions_energy_scale

  end subroutine runtime_pretty_print


end module runtime_init_module
