
! DO NOT EDIT THIS FILE!!!
!
! This file is automatically generated by write_network.py at
! compile-time.
!
! To modify the species carried by the network, edit the appropriate inputs
! file.

! An automatically generated "null" network.  This provides the properties
! of a set of non-reacting species.
!
! nspec            -- the number of species
! naux             -- the number of auxiliary variables
!
! aion             -- atomic number
! zion             -- proton number
!
! spec_names       -- the name of the isotope
! short_spec_names -- an abbreviated form of the species name
!
! aux_names        -- the name of the auxiliary variable
! short_aux_names  -- an abbreviated form of the auxiliary variable


module actual_network

  use amrex_fort_module, only : rt => amrex_real

  implicit none

  integer, parameter :: nspec = 11
  integer, parameter :: nspec_evolve = 11
  integer, parameter :: naux =  0

  character (len=16), save :: spec_names(nspec) 
  character (len= 5), save :: short_spec_names(nspec)
  character (len=16), save :: aux_names(naux)
  character (len= 5), save :: short_aux_names(naux)

  double precision, allocatable, save :: aion(:), zion(:)

  !$acc declare create(aion, zion)

#ifdef AMREX_USE_CUDA
  attributes(managed) :: aion, zion
#endif

  integer, parameter :: nrates = 0
  integer, parameter :: num_rate_groups = 0

contains
  
  subroutine actual_network_init

    spec_names(1) = "neon-20"
    spec_names(2) = "oxygen-16"
    spec_names(3) = "oxygen-20"
    spec_names(4) = "magnesium-24"
    spec_names(5) = "fluorine-20"
    spec_names(6) = "helium-4"
    spec_names(7) = "aluminum-27"
    spec_names(8) = "silicon-28"
    spec_names(9) = "sulfur-32"
    spec_names(10) = "phosphorus-31"
    spec_names(11) = "proton"

    short_spec_names(1) = "Ne20"
    short_spec_names(2) = "O16"
    short_spec_names(3) = "O20"
    short_spec_names(4) = "Mg24"
    short_spec_names(5) = "F20"
    short_spec_names(6) = "He4"
    short_spec_names(7) = "Al27"
    short_spec_names(8) = "Si28"
    short_spec_names(9) = "S32"
    short_spec_names(10) = "P31"
    short_spec_names(11) = "p"

    allocate(aion(nspec))
    allocate(zion(nspec))

    aion(1) = 20.0
    aion(2) = 16.0
    aion(3) = 20.0
    aion(4) = 24.0
    aion(5) = 20.0
    aion(6) = 4.0
    aion(7) = 27.0
    aion(8) = 28.0
    aion(9) = 32.0
    aion(10) = 31.0
    aion(11) = 1.0

    zion(1) = 10.0
    zion(2) = 8.0
    zion(3) = 8.0
    zion(4) = 12.0
    zion(5) = 9.0
    zion(6) = 2.0
    zion(7) = 13.0
    zion(8) = 14.0
    zion(9) = 16.0
    zion(10) = 15.0
    zion(11) = 1.0


    !$acc update device(aion, zion)

  end subroutine actual_network_init



  subroutine actual_network_finalize

    implicit none

    deallocate(aion)
    deallocate(zion)

  end subroutine actual_network_finalize

end module actual_network
